version: "3"

services:
  app:
    build: .
    container_name: flask-api
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    ports:
      - 27017:27017
